[functions.import-excel]
verify_jwt = false

[functions.archive-event]
verify_jwt = false

[functions.delete-routine]
verify_jwt = false

[functions.delete-judge]
verify_jwt = false

[functions.upsert-judge]
verify_jwt = false

[functions.update-routine]
verify_jwt = false
